<a href="https://colab.research.google.com/github/rootvesh/rootvesh/blob/main/CS_B_PARCT_4_MATRIX_OPERATIONS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
matrix operations 

In [1]:
# Python program to inverse
# a matrix using numpy
  
# Import required package
import numpy as np
  
# Taking a 3 * 3 matrix
A = np.array([[4, 6, 2],
              [4, -3, 5],
              [2, 8, 7]])
  
# Calculating the inverse of the matrix
print(np.linalg.inv(A))

[[ 0.22101449  0.0942029  -0.13043478]
 [ 0.06521739 -0.08695652  0.04347826]
 [-0.13768116  0.07246377  0.13043478]]


In [4]:
import numpy as np
B=np.array([[1,9,4],[2,2,6],[7,7,7]])
print(np.linalg.inv(B))

[[-0.125      -0.15625     0.20535714]
 [ 0.125      -0.09375     0.00892857]
 [ 0.          0.25       -0.07142857]]


In [5]:
print(np.linalg.det(B))

223.99999999999994


In [6]:
print(np.linalg.det(A))

-275.9999999999999


In [7]:
C=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
print(np.linalg.det(C))

0.0


In [11]:
print(np.linalg.matrix_rank(C))

2
