<a href="https://colab.research.google.com/github/rootvesh/rootvesh/blob/main/Mechanical_Practical_4_Matrix_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Matrix Operations 

In [3]:
# Python program to inverse
# a matrix using numpy
# Import required package
import numpy as np
# We wanto find the Inverse of the Matrix A,Here A is 3X3 Matrix
A=np.array([[1,4 ,7],[2,3,9],[5,2,8]])
print(A)


[[1 4 7]
 [2 3 9]
 [5 2 8]]


In [5]:
print("The inverse of the Matrix A is :\n",np.linalg.inv(A))

The inverse of the Matrix A is :
 [[ 0.13333333 -0.4         0.33333333]
 [ 0.64444444 -0.6         0.11111111]
 [-0.24444444  0.4        -0.11111111]]


In [6]:
print("The determinat of the Matrix A is :\n",np.linalg.det(A))

The determinat of the Matrix A is :
 44.99999999999997


In [7]:
# Importing numpy as np
import numpy as np
 
 
# Rank of a matrix
print("Rank of A:", np.linalg.matrix_rank(A))
 
# Trace of matrix A
print("\nTrace of A:", np.trace(A))
 
# Determinant of a matrix
print("\nDeterminant of A:", np.linalg.det(A))
 
# Inverse of matrix A
print("\nInverse of A:\n", np.linalg.inv(A))
 
print("\nMatrix A raised to power 3:\n",
           np.linalg.matrix_power(A, 3))

Rank of A: 3

Trace of A: 12

Determinant of A: 44.99999999999997

Inverse of A:
 [[ 0.13333333 -0.4         0.33333333]
 [ 0.64444444 -0.6         0.11111111]
 [-0.24444444  0.4        -0.11111111]]

Matrix A raised to power 3:
 [[ 599  464 1370]
 [ 688  543 1590]
 [ 718  556 1657]]


In [8]:
# You need to install numpy in order to import it
import numpy as np
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)
print("\n")
print(matrix.T)

[[1 2 3]
 [4 5 6]]


[[1 4]
 [2 5]
 [3 6]]


In [15]:
print(np.linalg.eigvals(A))

[14.07448299+0.j         -1.03724149+1.45650459j -1.03724149-1.45650459j]


In [17]:
B=np.array([[1,0,0],[0,3,0],[0,0,8]])
print(B)

[[1 0 0]
 [0 3 0]
 [0 0 8]]


In [18]:
print(" The eigen values of the matrix B are:\n",np.linalg.eigvals(B))

 The eigen valuess of the matrix B are:
 [1. 3. 8.]


In [21]:
print(" The eigen values of the matrix B are:\n",np.linalg.eig(B))

 The eigen values of the matrix B are:
 (array([1., 3., 8.]), array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]]))


In [23]:
print("the Matrix multiplication of A and B is:\n",np.matrix.dot(A,B))

the Matrix multiplication of A and B is:
 [[ 1 12 56]
 [ 2  9 72]
 [ 5  6 64]]


In [31]:
#Example-1-Defining Function-Using Bisection Method find real root of the eqn x^3-5x-9=0
def f(x):
    return x**3-5*x-9

# Implementing Bisection Method
def bisection(x0,x1,e):
    step = 1
    print('\n\n*** BISECTION METHOD IMPLEMENTATION ***')
    condition = True
    while condition:
        x2 = (x0 + x1)/2
        print('Iteration-%d, x2 = %0.6f and f(x2) = %0.6f' % (step, x2, f(x2)))

        if f(x0) * f(x2) < 0:
            x1 = x2
        else:
            x0 = x2
        
        step = step + 1
        condition = abs(f(x2)) > e

    print('\nRequired Root is : %0.8f' % x2)


# Input Section
x0 = input('First Guess: ')
x1 = input('Second Guess: ')
e = input('Tolerable Error: ')

# Converting input to float
x0 = float(x0)
x1 = float(x1)
e = float(e)

#Note: You can combine above two section like this
# x0 = float(input('First Guess: '))
# x1 = float(input('Second Guess: '))
# e = float(input('Tolerable Error: '))


# Checking Correctness of initial guess values and bisecting
if f(x0) * f(x1) > 0.0:
    print('Given guess values do not bracket the root.')
    print('Try Again with different guess values.')
else:
    bisection(x0,x1,e)

First Guess: 2
Second Guess: 3
Tolerable Error: 0.00001


*** BISECTION METHOD IMPLEMENTATION ***
Iteration-1, x2 = 2.500000 and f(x2) = -5.875000
Iteration-2, x2 = 2.750000 and f(x2) = -1.953125
Iteration-3, x2 = 2.875000 and f(x2) = 0.388672
Iteration-4, x2 = 2.812500 and f(x2) = -0.815186
Iteration-5, x2 = 2.843750 and f(x2) = -0.221588
Iteration-6, x2 = 2.859375 and f(x2) = 0.081448
Iteration-7, x2 = 2.851562 and f(x2) = -0.070592
Iteration-8, x2 = 2.855469 and f(x2) = 0.005297
Iteration-9, x2 = 2.853516 and f(x2) = -0.032680
Iteration-10, x2 = 2.854492 and f(x2) = -0.013700
Iteration-11, x2 = 2.854980 and f(x2) = -0.004204
Iteration-12, x2 = 2.855225 and f(x2) = 0.000546
Iteration-13, x2 = 2.855103 and f(x2) = -0.001829
Iteration-14, x2 = 2.855164 and f(x2) = -0.000641
Iteration-15, x2 = 2.855194 and f(x2) = -0.000048
Iteration-16, x2 = 2.855209 and f(x2) = 0.000249
Iteration-17, x2 = 2.855202 and f(x2) = 0.000101
Iteration-18, x2 = 2.855198 and f(x2) = 0.000027
Iteration-19, x2 =

In [33]:
#Example-2-Defining Function-Using Bisection Method find real root of the eqn x^3-5x-9=0
def f(x):
    return x**3-x-1

# Implementing Bisection Method
def bisection(x0,x1,e):
    step = 1
    print('\n\n*** BISECTION METHOD IMPLEMENTATION ***')
    condition = True
    while condition:
        x2 = (x0 + x1)/2
        print('Iteration-%d, x2 = %0.6f and f(x2) = %0.6f' % (step, x2, f(x2)))

        if f(x0) * f(x2) < 0:
            x1 = x2
        else:
            x0 = x2
        
        step = step + 1
        condition = abs(f(x2)) > e

    print('\nRequired Root is : %0.8f' % x2)


# Input Section
x0 = input('First Guess: ')
x1 = input('Second Guess: ')
e = input('Tolerable Error: ')

# Converting input to float
x0 = float(x0)
x1 = float(x1)
e = float(e)

#Note: You can combine above two section like this
# x0 = float(input('First Guess: '))
# x1 = float(input('Second Guess: '))
# e = float(input('Tolerable Error: '))


# Checking Correctness of initial guess values and bisecting
if f(x0) * f(x1) > 0.0:
    print('Given guess values do not bracket the root.')
    print('Try Again with different guess values.')
else:
    bisection(x0,x1,e)

First Guess: 0
Second Guess: 2
Tolerable Error: 0.00001


*** BISECTION METHOD IMPLEMENTATION ***
Iteration-1, x2 = 1.000000 and f(x2) = -1.000000
Iteration-2, x2 = 1.500000 and f(x2) = 0.875000
Iteration-3, x2 = 1.250000 and f(x2) = -0.296875
Iteration-4, x2 = 1.375000 and f(x2) = 0.224609
Iteration-5, x2 = 1.312500 and f(x2) = -0.051514
Iteration-6, x2 = 1.343750 and f(x2) = 0.082611
Iteration-7, x2 = 1.328125 and f(x2) = 0.014576
Iteration-8, x2 = 1.320312 and f(x2) = -0.018711
Iteration-9, x2 = 1.324219 and f(x2) = -0.002128
Iteration-10, x2 = 1.326172 and f(x2) = 0.006209
Iteration-11, x2 = 1.325195 and f(x2) = 0.002037
Iteration-12, x2 = 1.324707 and f(x2) = -0.000047
Iteration-13, x2 = 1.324951 and f(x2) = 0.000995
Iteration-14, x2 = 1.324829 and f(x2) = 0.000474
Iteration-15, x2 = 1.324768 and f(x2) = 0.000214
Iteration-16, x2 = 1.324738 and f(x2) = 0.000084
Iteration-17, x2 = 1.324722 and f(x2) = 0.000018
Iteration-18, x2 = 1.324715 and f(x2) = -0.000014
Iteration-19, x2 = 1.3

In [34]:
#Example-3-Defining Function-Using Bisection Method find real root of the eqn x^3-5x-9=0
def f(x):
    return 2*x**3-2*x-5

# Implementing Bisection Method
def bisection(x0,x1,e):
    step = 1
    print('\n\n*** BISECTION METHOD IMPLEMENTATION ***')
    condition = True
    while condition:
        x2 = (x0 + x1)/2
        print('Iteration-%d, x2 = %0.6f and f(x2) = %0.6f' % (step, x2, f(x2)))

        if f(x0) * f(x2) < 0:
            x1 = x2
        else:
            x0 = x2
        
        step = step + 1
        condition = abs(f(x2)) > e

    print('\nRequired Root is : %0.8f' % x2)


# Input Section
x0 = input('First Guess: ')
x1 = input('Second Guess: ')
e = input('Tolerable Error: ')

# Converting input to float
x0 = float(x0)
x1 = float(x1)
e = float(e)

#Note: You can combine above two section like this
# x0 = float(input('First Guess: '))
# x1 = float(input('Second Guess: '))
# e = float(input('Tolerable Error: '))


# Checking Correctness of initial guess values and bisecting
if f(x0) * f(x1) > 0.0:
    print('Given guess values do not bracket the root.')
    print('Try Again with different guess values.')
else:
    bisection(x0,x1,e)

First Guess: 0
Second Guess: 2
Tolerable Error: 0.001


*** BISECTION METHOD IMPLEMENTATION ***
Iteration-1, x2 = 1.000000 and f(x2) = -5.000000
Iteration-2, x2 = 1.500000 and f(x2) = -1.250000
Iteration-3, x2 = 1.750000 and f(x2) = 2.218750
Iteration-4, x2 = 1.625000 and f(x2) = 0.332031
Iteration-5, x2 = 1.562500 and f(x2) = -0.495605
Iteration-6, x2 = 1.593750 and f(x2) = -0.091125
Iteration-7, x2 = 1.609375 and f(x2) = 0.118095
Iteration-8, x2 = 1.601562 and f(x2) = 0.012898
Iteration-9, x2 = 1.597656 and f(x2) = -0.039260
Iteration-10, x2 = 1.599609 and f(x2) = -0.013217
Iteration-11, x2 = 1.600586 and f(x2) = -0.000169

Required Root is : 1.60058594
